---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunneld-controller
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunneld.io
  resources:
  - tunnelgroups
  - tunnelkeys
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunneld.io
  resources:
  - tunnelgroups/status
  - tunnelkeys/status
  - tunnels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tunneld.io
  resources:
  - tunnels/finalizers
  verbs:
  - update
