# Build stage
FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Use Buildx TARGETARCH to cross-compile
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -o tunnelctl ./cmd/tunnelctl/main.go

# Runtime stage
FROM alpine:3.21

# Copy the binary from the builder stage
COPY --from=builder /app/tunnelctl /usr/local/bin/tunnelctl

ENTRYPOINT ["/usr/local/bin/tunnelctl"]
