# syntax=docker/dockerfile:1
FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-amd64} \
    go build -trimpath -ldflags "-s -w" -o /out/tunneld-controller ./cmd/tunneld-controller

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/tunneld-controller /usr/local/bin/tunneld-controller
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/tunneld-controller"]
