// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: spec.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DependsOn []string               `protobuf:"bytes,2,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*TunnelSpec_Ssh
	//	*TunnelSpec_Kubectl
	Type            isTunnelSpec_Type    `protobuf_oneof:"type"`
	Health          *HealthCheckSpec     `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"`
	Restart         *RestartPolicySpec   `protobuf:"bytes,6,opt,name=restart,proto3" json:"restart,omitempty"`
	StartupTimeout  *durationpb.Duration `protobuf:"bytes,7,opt,name=startup_timeout,json=startupTimeout,proto3" json:"startup_timeout,omitempty"`
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,8,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TunnelSpec) Reset() {
	*x = TunnelSpec{}
	mi := &file_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelSpec) ProtoMessage() {}

func (x *TunnelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelSpec.ProtoReflect.Descriptor instead.
func (*TunnelSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelSpec) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TunnelSpec) GetType() isTunnelSpec_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TunnelSpec) GetSsh() *SSHSpec {
	if x != nil {
		if x, ok := x.Type.(*TunnelSpec_Ssh); ok {
			return x.Ssh
		}
	}
	return nil
}

func (x *TunnelSpec) GetKubectl() *KubectlSpec {
	if x != nil {
		if x, ok := x.Type.(*TunnelSpec_Kubectl); ok {
			return x.Kubectl
		}
	}
	return nil
}

func (x *TunnelSpec) GetHealth() *HealthCheckSpec {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *TunnelSpec) GetRestart() *RestartPolicySpec {
	if x != nil {
		return x.Restart
	}
	return nil
}

func (x *TunnelSpec) GetStartupTimeout() *durationpb.Duration {
	if x != nil {
		return x.StartupTimeout
	}
	return nil
}

func (x *TunnelSpec) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type isTunnelSpec_Type interface {
	isTunnelSpec_Type()
}

type TunnelSpec_Ssh struct {
	Ssh *SSHSpec `protobuf:"bytes,3,opt,name=ssh,proto3,oneof"`
}

type TunnelSpec_Kubectl struct {
	Kubectl *KubectlSpec `protobuf:"bytes,4,opt,name=kubectl,proto3,oneof"`
}

func (*TunnelSpec_Ssh) isTunnelSpec_Type() {}

func (*TunnelSpec_Kubectl) isTunnelSpec_Type() {}

type SSHSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IdentityFile  string                 `protobuf:"bytes,4,opt,name=identity_file,json=identityFile,proto3" json:"identity_file,omitempty"`
	LocalForwards []*SSHForward          `protobuf:"bytes,5,rep,name=local_forwards,json=localForwards,proto3" json:"local_forwards,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSpec) Reset() {
	*x = SSHSpec{}
	mi := &file_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSpec) ProtoMessage() {}

func (x *SSHSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSpec.ProtoReflect.Descriptor instead.
func (*SSHSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{1}
}

func (x *SSHSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SSHSpec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SSHSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SSHSpec) GetIdentityFile() string {
	if x != nil {
		return x.IdentityFile
	}
	return ""
}

func (x *SSHSpec) GetLocalForwards() []*SSHForward {
	if x != nil {
		return x.LocalForwards
	}
	return nil
}

func (x *SSHSpec) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SSHForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenAddress string                 `protobuf:"bytes,1,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	TargetHost    string                 `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHForward) Reset() {
	*x = SSHForward{}
	mi := &file_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHForward) ProtoMessage() {}

func (x *SSHForward) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHForward.ProtoReflect.Descriptor instead.
func (*SSHForward) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{2}
}

func (x *SSHForward) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *SSHForward) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *SSHForward) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *SSHForward) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type KubectlSpec struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Kubeconfig            string                 `protobuf:"bytes,1,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	Context               string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Namespace             string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Resource              string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Forwards              []*KubectlForward      `protobuf:"bytes,5,rep,name=forwards,proto3" json:"forwards,omitempty"`
	ApiServer             string                 `protobuf:"bytes,6,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	InsecureSkipTlsVerify bool                   `protobuf:"varint,7,opt,name=insecure_skip_tls_verify,json=insecureSkipTlsVerify,proto3" json:"insecure_skip_tls_verify,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *KubectlSpec) Reset() {
	*x = KubectlSpec{}
	mi := &file_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubectlSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubectlSpec) ProtoMessage() {}

func (x *KubectlSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubectlSpec.ProtoReflect.Descriptor instead.
func (*KubectlSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{3}
}

func (x *KubectlSpec) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *KubectlSpec) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *KubectlSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubectlSpec) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *KubectlSpec) GetForwards() []*KubectlForward {
	if x != nil {
		return x.Forwards
	}
	return nil
}

func (x *KubectlSpec) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *KubectlSpec) GetInsecureSkipTlsVerify() bool {
	if x != nil {
		return x.InsecureSkipTlsVerify
	}
	return false
}

type KubectlForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalAddress  string                 `protobuf:"bytes,1,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	LocalPort     int32                  `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    int32                  `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubectlForward) Reset() {
	*x = KubectlForward{}
	mi := &file_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubectlForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubectlForward) ProtoMessage() {}

func (x *KubectlForward) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubectlForward.ProtoReflect.Descriptor instead.
func (*KubectlForward) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{4}
}

func (x *KubectlForward) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *KubectlForward) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *KubectlForward) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type HealthCheckSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Interval       *durationpb.Duration   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	StartupTimeout *durationpb.Duration   `protobuf:"bytes,5,opt,name=startup_timeout,json=startupTimeout,proto3" json:"startup_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckSpec) Reset() {
	*x = HealthCheckSpec{}
	mi := &file_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckSpec) ProtoMessage() {}

func (x *HealthCheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckSpec.ProtoReflect.Descriptor instead.
func (*HealthCheckSpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheckSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HealthCheckSpec) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *HealthCheckSpec) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HealthCheckSpec) GetStartupTimeout() *durationpb.Duration {
	if x != nil {
		return x.StartupTimeout
	}
	return nil
}

type RestartPolicySpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        string                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"` // always, on-failure, never
	Delay         *durationpb.Duration   `protobuf:"bytes,2,opt,name=delay,proto3" json:"delay,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,3,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPolicySpec) Reset() {
	*x = RestartPolicySpec{}
	mi := &file_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicySpec) ProtoMessage() {}

func (x *RestartPolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicySpec.ProtoReflect.Descriptor instead.
func (*RestartPolicySpec) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{6}
}

func (x *RestartPolicySpec) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *RestartPolicySpec) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *RestartPolicySpec) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

var File_spec_proto protoreflect.FileDescriptor

const file_spec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spec.proto\x12\ttunnel.v1\x1a\x1egoogle/protobuf/duration.proto\"\x99\x03\n" +
	"\n" +
	"TunnelSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x02 \x03(\tR\tdependsOn\x12&\n" +
	"\x03ssh\x18\x03 \x01(\v2\x12.tunnel.v1.SSHSpecH\x00R\x03ssh\x122\n" +
	"\akubectl\x18\x04 \x01(\v2\x16.tunnel.v1.KubectlSpecH\x00R\akubectl\x122\n" +
	"\x06health\x18\x05 \x01(\v2\x1a.tunnel.v1.HealthCheckSpecR\x06health\x126\n" +
	"\arestart\x18\x06 \x01(\v2\x1c.tunnel.v1.RestartPolicySpecR\arestart\x12B\n" +
	"\x0fstartup_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0estartupTimeout\x12D\n" +
	"\x10shutdown_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeoutB\x06\n" +
	"\x04type\"\x9f\x02\n" +
	"\aSSHSpec\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12#\n" +
	"\ridentity_file\x18\x04 \x01(\tR\fidentityFile\x12<\n" +
	"\x0elocal_forwards\x18\x05 \x03(\v2\x15.tunnel.v1.SSHForwardR\rlocalForwards\x129\n" +
	"\aoptions\x18\x06 \x03(\v2\x1f.tunnel.v1.SSHSpec.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\n" +
	"SSHForward\x12%\n" +
	"\x0elisten_address\x18\x01 \x01(\tR\rlistenAddress\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\"\x90\x02\n" +
	"\vKubectlSpec\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\tR\n" +
	"kubeconfig\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x125\n" +
	"\bforwards\x18\x05 \x03(\v2\x19.tunnel.v1.KubectlForwardR\bforwards\x12\x1d\n" +
	"\n" +
	"api_server\x18\x06 \x01(\tR\tapiServer\x127\n" +
	"\x18insecure_skip_tls_verify\x18\a \x01(\bR\x15insecureSkipTlsVerify\"u\n" +
	"\x0eKubectlForward\x12#\n" +
	"\rlocal_address\x18\x01 \x01(\tR\flocalAddress\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\x05R\n" +
	"remotePort\"\xef\x01\n" +
	"\x0fHealthCheckSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12B\n" +
	"\x0fstartup_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0estartupTimeout\"\x7f\n" +
	"\x11RestartPolicySpec\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12/\n" +
	"\x05delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12!\n" +
	"\fmax_attempts\x18\x03 \x01(\x05R\vmaxAttemptsB\x1dZ\x1btunneld/pkg/api/v1;tunnelv1b\x06proto3"

var (
	file_spec_proto_rawDescOnce sync.Once
	file_spec_proto_rawDescData []byte
)

func file_spec_proto_rawDescGZIP() []byte {
	file_spec_proto_rawDescOnce.Do(func() {
		file_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)))
	})
	return file_spec_proto_rawDescData
}

var file_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spec_proto_goTypes = []any{
	(*TunnelSpec)(nil),          // 0: tunnel.v1.TunnelSpec
	(*SSHSpec)(nil),             // 1: tunnel.v1.SSHSpec
	(*SSHForward)(nil),          // 2: tunnel.v1.SSHForward
	(*KubectlSpec)(nil),         // 3: tunnel.v1.KubectlSpec
	(*KubectlForward)(nil),      // 4: tunnel.v1.KubectlForward
	(*HealthCheckSpec)(nil),     // 5: tunnel.v1.HealthCheckSpec
	(*RestartPolicySpec)(nil),   // 6: tunnel.v1.RestartPolicySpec
	nil,                         // 7: tunnel.v1.SSHSpec.OptionsEntry
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_spec_proto_depIdxs = []int32{
	1,  // 0: tunnel.v1.TunnelSpec.ssh:type_name -> tunnel.v1.SSHSpec
	3,  // 1: tunnel.v1.TunnelSpec.kubectl:type_name -> tunnel.v1.KubectlSpec
	5,  // 2: tunnel.v1.TunnelSpec.health:type_name -> tunnel.v1.HealthCheckSpec
	6,  // 3: tunnel.v1.TunnelSpec.restart:type_name -> tunnel.v1.RestartPolicySpec
	8,  // 4: tunnel.v1.TunnelSpec.startup_timeout:type_name -> google.protobuf.Duration
	8,  // 5: tunnel.v1.TunnelSpec.shutdown_timeout:type_name -> google.protobuf.Duration
	2,  // 6: tunnel.v1.SSHSpec.local_forwards:type_name -> tunnel.v1.SSHForward
	7,  // 7: tunnel.v1.SSHSpec.options:type_name -> tunnel.v1.SSHSpec.OptionsEntry
	4,  // 8: tunnel.v1.KubectlSpec.forwards:type_name -> tunnel.v1.KubectlForward
	8,  // 9: tunnel.v1.HealthCheckSpec.interval:type_name -> google.protobuf.Duration
	8,  // 10: tunnel.v1.HealthCheckSpec.timeout:type_name -> google.protobuf.Duration
	8,  // 11: tunnel.v1.HealthCheckSpec.startup_timeout:type_name -> google.protobuf.Duration
	8,  // 12: tunnel.v1.RestartPolicySpec.delay:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_spec_proto_init() }
func file_spec_proto_init() {
	if File_spec_proto != nil {
		return
	}
	file_spec_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelSpec_Ssh)(nil),
		(*TunnelSpec_Kubectl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_goTypes,
		DependencyIndexes: file_spec_proto_depIdxs,
		MessageInfos:      file_spec_proto_msgTypes,
	}.Build()
	File_spec_proto = out.File
	file_spec_proto_goTypes = nil
	file_spec_proto_depIdxs = nil
}
